"""Gold-standard word families for family assertions and merge metrics.

Each key is the expected family lemma; the value lists surface forms that
must all map to that key. Singleton families at the bottom are deliberate
over-merge traps: related spellings / derivations that must stay separate
under the conservative rule set but collapse under aggressive rules.
"""

FAMILIES = {
    # irregular / suppletive verbs
    "be": ["be", "am", "is", "are", "was", "were", "been", "being"],
    "go": ["go", "goes", "going", "went", "gone"],
    "do": ["do", "does", "doing", "done", "did"],
    "have": ["have", "has", "had"],
    "make": ["make", "makes", "making", "made"],
    "take": ["take", "takes", "taking", "took"],
    "run": ["run", "runs", "running", "ran"],
    "swim": ["swim", "swims", "swimming", "swam", "swum"],
    "write": ["write", "writes", "writing", "wrote", "written"],
    "eat": ["eat", "eats", "eating", "ate"],
    "say": ["say", "says", "said"],
    "see": ["see", "sees", "saw", "seen"],
    "know": ["know", "knows", "knew", "known"],
    "give": ["give", "gives", "giving", "gave", "given"],
    "find": ["find", "finds", "found"],
    "think": ["think", "thinks", "thought"],
    "come": ["come", "comes", "coming", "came"],
    "sing": ["sing", "sings", "singing", "sang", "sung"],
    "sit": ["sit", "sits", "sitting", "sat"],
    "win": ["win", "wins", "winning", "won"],
    "speak": ["speak", "speaks", "speaking", "spoke", "spoken"],
    "break": ["break", "breaks", "broke", "broken"],
    "choose": ["choose", "chooses", "chose", "chosen"],
    "drive": ["drive", "drives", "driving", "drove", "driven"],
    "fall": ["fall", "falls", "falling", "fell", "fallen"],
    "fly": ["fly", "flies", "flying", "flew", "flown"],
    "grow": ["grow", "grows", "growing", "grew", "grown"],
    "throw": ["throw", "throws", "throwing", "threw", "thrown"],
    "wear": ["wear", "wears", "wearing", "wore", "worn"],
    "tear": ["tear", "tears", "tore", "torn"],
    "teach": ["teach", "teaches", "teaching", "taught"],
    "buy": ["buy", "buys", "buying", "bought"],
    "bring": ["bring", "brings", "brought"],
    "sleep": ["sleep", "sleeps", "sleeping", "slept"],
    "feel": ["feel", "feels", "feeling", "felt"],
    "leave": ["leave", "leaves", "leaving", "left"],
    "stand": ["stand", "stands", "standing", "stood"],
    "understand": ["understand", "understands", "understood"],
    "begin": ["begin", "begins", "beginning", "began", "begun"],
    "rise": ["rise", "rises", "rose", "risen"],
    "lie": ["lie", "lies", "lying", "lay", "lain"],
    "die": ["die", "dies", "dying", "died"],
    "tie": ["tie", "ties", "tying", "tied"],
    # regular inflections exercising the rules
    "stop": ["stop", "stops", "stopped", "stopping"],
    "bake": ["bake", "bakes", "baked", "baking"],
    "hope": ["hope", "hopes", "hoped", "hoping"],
    "play": ["play", "plays", "played", "playing"],
    "walk": ["walk", "walks", "walked", "walking"],
    "watch": ["watch", "watches", "watched", "watching"],
    "box": ["box", "boxes"],
    "class": ["class", "classes"],
    "study": ["study", "studies", "studied", "studying"],
    "try": ["try", "tries", "tried", "trying"],
    "cry": ["cry", "cries", "cried", "crying"],
    "carry": ["carry", "carries", "carried", "carrying"],
    "cookie": ["cookie", "cookies"],
    # irregular comparison
    "good": ["good", "better", "best"],
    "bad": ["bad", "worse", "worst"],
    # irregular plurals
    "child": ["child", "children"],
    "man": ["man", "men"],
    "woman": ["woman", "women"],
    "mouse": ["mouse", "mice"],
    "goose": ["goose", "geese"],
    "tooth": ["tooth", "teeth"],
    "foot": ["foot", "feet"],
    "person": ["person", "people"],
    # uppercase acronym families
    "API": ["API", "APIs"],
    "URL": ["URL", "URLs"],
    "FAQ": ["FAQ", "FAQs"],
    "NASA": ["NASA"],
    # non-English characters: each is its own family, kept verbatim
    "café": ["café"],
    "cafe": ["cafe"],
    "naïve": ["naïve"],
    "naive": ["naive"],
    "über": ["über"],
    "你好": ["你好"],
    "München": ["München"],
    # ---- over-merge traps: distinct families that aggressive rules collapse
    "universe": ["universe"],
    "university": ["university"],
    "general": ["general"],
    "generous": ["generous"],
    "personal": ["personal"],
    "happiness": ["happiness"],
    "happy": ["happy"],
    "nation": ["nation"],
    "national": ["national"],
    "nature": ["nature"],
    "natural": ["natural"],
}
